USE COLEGIO
GO
--DROP TABLE IF EXISTS COLEGIO
--DROP TABLE IF EXISTS CURSOS
--DROP TABLE IF EXISTS ALUMNOS
--DROP TABLE IF EXISTS ASISTENCIA

--CREATE TABLE COLEGIO (
--COD_COLEGIO INT NOT NULL,
--NOMBRE VARCHAR (100) NOT NULL,
--DIRECCION VARCHAR (100) NOT NULL,
--TELEFONO INT NOT NULL,
--PRIMARY KEY (COD_COLEGIO)
--)
--CREATE TABLE CURSOS (
--COD_CURSOS INT NOT NULL,
--COD_COLEGIO INT NOT NULL,
--SALA VARCHAR (100) NOT NULL,
--SECCION VARCHAR (100) NOT NULL,
--ASIGNATURA VARCHAR (100) NOT NULL,
--PRIMARY KEY (COD_CURSOS),
--CONSTRAINT FK_CURSOS FOREIGN KEY (COD_COLEGIO )
--REFERENCES CURSOS (COD_CURSOS)
--)
--CREATE TABLE PROFESORES (
--COD_PROFESORES INT NOT NULL,
--COD_CURSOS INT NOT NULL,
--NOMBRE VARCHAR (100) NOT NULL,
--APELLIDO VARCHAR (100) NOT NULL,
--RUT VARCHAR (20) NOT NULL,
--PRIMARY KEY (COD_PROFESORES),
--CONSTRAINT FK_PROFESORES FOREIGN KEY (COD_CURSOS)
--REFERENCES PROFESORES (COD_PROFESORES)
--)
--CREATE TABLE ASISTENCIA (
--COD_ASISTENCIA INT NOT NULL,
--COD_ALUMNOS INT NOT NULL,
--FECHA_INICIO DATETIME NOT NULL,
--FECHA_FIN DATETIME  NOT NULL
--PRIMARY KEY (COD_ASISTENCIA),
--CONSTRAINT FK_ASISTENCIA_ALUMNOS FOREIGN KEY (COD_ALUMNOS)
--REFERENCES ASISTENCIA (COD_ASISTENCIA)
)
--CREATE TABLE ALUMNOS (
--COD_ALUMNOS INT NOT NULL,
--COD_CURSOS INT NOT NULL,
--NOMBRE VARCHAR (100) NOT NULL,
--APELLIDO VARCHAR (100) NOT NULL,
--DIRECCION VARCHAR (100) NOT NULL,
--TELEFONO INT NOT NULL,
--PRIMARY KEY (COD_ALUMNOS),
--CONSTRAINT FK_ALUMNOS FOREIGN KEY (COD_CURSOS )
--REFERENCES ALUMNOS (COD_ALUMNOS)
)

--------------insersiones tabla COLEGIO---------------------------------

INSERT INTO COLEGIO VALUES (1, 'LA PAZ','VILLA LAS CADENAS 775', 8158533
)
INSERT INTO COLEGIO VALUES (22, 'COLEGIO LA PAZ','VILLA LAS CADENAS 775 TALAGANTE', 028158533
)


--------------insersiones tabla CURSOS---------------------------------


INSERT INTO CURSOS VALUES (11, 11,'SALA 1',1 ,'LENGUAJE'
)
INSERT INTO CURSOS VALUES (22, 11,'SALA 2',2 ,'MATEMATICAS'
)
INSERT INTO CURSOS VALUES (7, 11,'SALA 3',3 ,'ARTES'
)
INSERT INTO CURSOS VALUES (33, 22,'KINDER',3 ,'MATEMATICA APLICADA'
)

--------------insersiones tabla ALUMNOS---------------------------------

INSERT INTO ALUMNOS VALUES (11, 11,'CARLOS','GOMEZ','LOS CIRUELOS' ,028458889
)
INSERT INTO ALUMNOS VALUES (10, 22,'CAROL','CIT','TESTO 06' ,0266657577
)
INSERT INTO ALUMNOS VALUES (7, 7,'CATHERINE','MISHT','VILLA OJOS DEL SALADO' ,0211567877
)
INSERT INTO ALUMNOS VALUES (33, 33,'WALTER','EL MAS PULENTO','VILLA COMO REY Y TOMA' ,0266666
)

--------------insersiones tabla profesor---------------------------------------

INSERT INTO PROFESORES VALUES (22,22,'MARIA','CARES',78158599
)
--------------insersiones tabla ASISTENCIA-------------------------------------
INSERT INTO ASISTENCIA VALUES (7,7,GETDATE(),''
)
-------------------SELECT DE TABLAS ----------------------------


SELECT 
* FROM COLEGIO

SELECT 
* FROM CURSOS

SELECT 
* FROM ALUMNOS

SELECT 
* FROM ASISTENCIA

SELECT 
* FROM PROFESORES
--------------------------------------ACTUALIZAR Y ELIMINR REGISTROS------------------------
--SELECT 
----UPDATE C SET
--COD_COLEGIO = 13
--FROM COLEGIO C
--WHERE COD_COLEGIO = 22 

--DELETE 
--FROM COLEGIO 
--WHERE COD_COLEGIO = 13
------------------------------------ACTUALIZAR Y ELIMINR REGISTROS------------------------{

------------------------------------INNER JOIN DE TABLAS------------------------
--select ALU.NOMBRE,ALU.APELLIDO, CIA.FECHA_INICIO, SOS.ASIGNATURA,SOS.COD_CURSOS, C.DIRECCION
--from [dbo].[COLEGIO] c inner join cursos sos on c.cod_colegio =  sos.cod_colegio
--inner join [dbo].[ALUMNOS] alu on alu.cod_cursos = sos.cod_cursos
--INNER JOIN ASISTENCIA CIA ON CIA.COD_ALUMNOS = ALU.COD_ALUMNOS
